### ISSUE TITLE
issue on android word

### ISSUE THREAD

**Issue by gurukiran-econote** [viralvaghela/Jwiki#6]
java.lang.NullPointerException: Cannot invoke "org.json.simple.JSONObject.get(Object)" because "jsonObjectOriginalImage" is null
Title :<span class="mw-page-title-main">Android</span>
Text : 
Image : 
	at com.wiki.Jwiki.getData(Jwiki.java:37)
	at com.wiki.Jwiki.<init>(Jwiki.java:19)
	at com.wiki.WikipediaSample.main(WikipediaSample.java:6)
         ||
        \/
when i use "android" word i get null pointer error on image please fix or remove image part or do try catch block for all three seperately so that one fails you can give source not found like that.

and also i tried to execute your project without using jar whick i took from jwiki repo but it gives "noclassdefFound error: okio/Buffer". i dont know know what to do.

Exception in thread "main" java.lang.NoClassDefFoundError: okio/Buffer
	at com.squareup.okhttp.HttpUrl.canonicalize(HttpUrl.java:1560)
	at com.squareup.okhttp.HttpUrl$Builder.push(HttpUrl.java:1105)
	at com.squareup.okhttp.HttpUrl$Builder.resolvePath(HttpUrl.java:1096)
	at com.squareup.okhttp.HttpUrl$Builder.parse(HttpUrl.java:1055)
	at com.squareup.okhttp.HttpUrl.parse(HttpUrl.java:596)
	at com.squareup.okhttp.Request$Builder.url(Request.java:162)
	at com.wiki.WikipediaSample.getData(WikipediaSample.java:32)
	at com.wiki.WikipediaSample.<init>(WikipediaSample.java:26)
	at com.wiki.WikipediaSample.main(WikipediaSample.java:13)
Caused by: java.lang.ClassNotFoundException: okio.Buffer
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 9 more

**Comment by viralvaghela** [comment]
Hi @gurukiran-econote , sure will look into this issue
